worlds:
    world:
        months:
            January:
                days: 31
                season: Makuru
            February:
                days: 28
                season: Djilba
            March:
                days: 31
                season: Djilba
            April:
                days: 30
                season: Kamba
            May:
                days: 31
                season: Kamba
            June:
                days: 30
                season: Birak
            July:
                days: 31
                season: Birak
            August:
                days: 31
                season: Bunuru
            September:
                days: 30
                season: Bunuru
            October:
                days: 31
                season: Djeran
            November:
                days: 30
                season: Djeran
            December:
                days: 31
                season: Makuru
        weekdays:
        - Sunday
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
seasons:
    Djilba:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.1_Djilba.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: RAIN
            ICE_DESERT: SNOW
            PLAINS: NONE
            RAINFOREST: RAIN
            SAVANNA: NONE
            SEASONAL_FOREST: NONE
            SHRUBLAND: RAIN
            SWAMPLAND: NONE
            TAIGA: SNOW
            TUNDRA: SNOW
    Kamba:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.1_Kamba.zip
        Biome_Weather:
            DESERT: RAIN
            FOREST: RAIN
            ICE_DESERT: RAIN
            PLAINS: RAIN
            RAINFOREST: RAIN
            SAVANNA: RAIN
            SEASONAL_FOREST: RAIN
            SHRUBLAND: NONE
            SWAMPLAND: RAIN
            TAIGA: SNOW
            TUNDRA: SNOW
    Birak:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.1_Birak.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: RAIN
            ICE_DESERT: NONE
            PLAINS: RAIN
            RAINFOREST: RAIN
            SAVANNA: RAIN
            SEASONAL_FOREST: RAIN
            SHRUBLAND: NONE
            SWAMPLAND: NONE
            TAIGA: SNOW
            TUNDRA: SNOW
    Bunuru:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.1_Bunuru.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: RAIN
            ICE_DESERT: SNOW
            PLAINS: NONE
            RAINFOREST: RAIN
            SAVANNA: RAIN
            SEASONAL_FOREST: RAIN
            SHRUBLAND: NONE
            SWAMPLAND: RAIN
            TAIGA: SNOW
            TUNDRA: SNOW
    Djeran:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.1_Djeran.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: RAIN
            ICE_DESERT: SNOW
            PLAINS: NONE
            RAINFOREST: RAIN
            SAVANNA: RAIN
            SEASONAL_FOREST: RAIN
            SHRUBLAND: RAIN
            SWAMPLAND: RAIN
            TAIGA: SNOW
            TUNDRA: SNOW
    Makuru:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.1_Makuru.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: SNOW
            ICE_DESERT: SNOW
            PLAINS: NONE
            RAINFOREST: NONE
            SAVANNA: NONE
            SEASONAL_FOREST: NONE
            SHRUBLAND: RAIN
            SWAMPLAND: NONE
            TAIGA: SNOW
            TUNDRA: SNOW
date_message: '{WEEKDAY} the {DATE}{MOD} of {MONTH} {YEAR}AN'
HUD_X: 0
HUD_Y: 10
