#===worlds that AmbientSeason is enabled for===
#worlds:
#    name of world for this calendar
#    world:
#        months in this calendar
#        months:
#            ===name of the month in this calendar===
#            January:
#                ===number of days in this month===
#                days: 31
#                ===season to use for this month===
#                season: Makuru
#        ===weekdays in this calendar===
#        weekdays:
#        - Sunday
#        - Monday
#        - Tuesday
#        - Wednesday
#        - Thursday
#        - Friday
#        - Saturday
#
#===seasons, usable in any calendar===
#seasons:
#    ===name of the season===
#    Djilba:
#        ===texture pack URL to use for the season===
#        URL: http://www.retributiongames.com/quandary/files/Quandary_4.2_5_Djilba.zip
#        ===List of weather by biome===
#        Biome_Weather:
#            ===Name of the Biome, and the weather type for this season in that biome               ===
#            ===Possible weather types are NONE, RAIN, SNOW, and RESET                              ===
#            ===Any biomes not listed will be RESET which resets to what it is in vanilla minecraft ===
#            DESERT: NONE
#            FOREST: RAIN
#            ICE_DESERT: SNOW
#            PLAINS: NONE
#            RAINFOREST: RAIN
#            SAVANNA: NONE
#            SEASONAL_FOREST: NONE
#            SHRUBLAND: RAIN
#            SWAMPLAND: NONE
#            TAIGA: SNOW
#            TUNDRA: SNOW
#
#===Date message that displays on the HUD                                           ===
#==={WEEKDAY} is the string for the day of the week                                 ===
#==={DATE} is the day of the month                                                  ===
#==={MOD} is 'st', 'nd', 'rd', 'th' modifiers after the date for English dates      ===
#==={MONTH} is the string for the month                                             ===
#==={YEAR} is the year                                                              ===
#===Message can be any combination of these things and text, including chat colors  ===
#date_message: '{WEEKDAY} the {DATE}{MOD} of {MONTH} {YEAR}AN'
#
#===Date message that displays on /date and new day notifications
#===If it exceeds 26 Characters (The limit for notifications) it will default to this internally  ===
#===Otherwise it will parse this like date_message                                                ===
#==={DATE} is the day of the month                                                                ===
#==={MONTH} is the month (number, not string)                                                     ===
#==={YEAR} is the year                                                                            ===
#short_date_message: '{DATE}/{MONTH}/{YEAR}'
#
#===X value for the HUD===
#HUD_X: 0
#
#===Y value for the HUD===
#HUD_Y: 10
worlds:
    world:
        months:
            January:
                days: 31
                season: Makuru
            February:
                days: 28
                season: Djilba
            March:
                days: 31
                season: Djilba
            April:
                days: 30
                season: Kamba
            May:
                days: 31
                season: Kamba
            June:
                days: 30
                season: Birak
            July:
                days: 31
                season: Birak
            August:
                days: 31
                season: Bunuru
            September:
                days: 30
                season: Bunuru
            October:
                days: 31
                season: Djeran
            November:
                days: 30
                season: Djeran
            December:
                days: 31
                season: Makuru
        weekdays:
        - Sunday
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday

seasons:
    Djilba:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.2_5_Djilba.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: RAIN
            ICE_DESERT: SNOW
            PLAINS: NONE
            RAINFOREST: RAIN
            SAVANNA: NONE
            SEASONAL_FOREST: NONE
            SHRUBLAND: RAIN
            SWAMPLAND: NONE
            TAIGA: SNOW
            TUNDRA: SNOW
    Kamba:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.2_6_Kamba.zip
        Biome_Weather:
            DESERT: RAIN
            FOREST: RAIN
            ICE_DESERT: RAIN
            PLAINS: RAIN
            RAINFOREST: RAIN
            SAVANNA: RAIN
            SEASONAL_FOREST: RAIN
            SHRUBLAND: NONE
            SWAMPLAND: RAIN
            TAIGA: SNOW
            TUNDRA: SNOW
    Birak:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.2_1_Birak.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: RAIN
            ICE_DESERT: NONE
            PLAINS: RAIN
            RAINFOREST: RAIN
            SAVANNA: RAIN
            SEASONAL_FOREST: RAIN
            SHRUBLAND: NONE
            SWAMPLAND: NONE
            TAIGA: SNOW
            TUNDRA: SNOW
    Bunuru:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.2_2_Bunuru.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: RAIN
            ICE_DESERT: SNOW
            PLAINS: NONE
            RAINFOREST: RAIN
            SAVANNA: RAIN
            SEASONAL_FOREST: RAIN
            SHRUBLAND: NONE
            SWAMPLAND: RAIN
            TAIGA: SNOW
            TUNDRA: SNOW
    Djeran:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.2_3_Djeran.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: RAIN
            ICE_DESERT: SNOW
            PLAINS: NONE
            RAINFOREST: RAIN
            SAVANNA: RAIN
            SEASONAL_FOREST: RAIN
            SHRUBLAND: RAIN
            SWAMPLAND: RAIN
            TAIGA: SNOW
            TUNDRA: SNOW
    Makuru:
        URL: http://www.retributiongames.com/quandary/files/Quandary_4.2_4_Makuru.zip
        Biome_Weather:
            DESERT: NONE
            FOREST: SNOW
            ICE_DESERT: SNOW
            PLAINS: NONE
            RAINFOREST: NONE
            SAVANNA: NONE
            SEASONAL_FOREST: NONE
            SHRUBLAND: RAIN
            SWAMPLAND: NONE
            TAIGA: SNOW
            TUNDRA: SNOW

date_message: '{WEEKDAY} the {DATE}{MOD} of {MONTH} {YEAR}AN'

short_date_message: '{DATE}/{MONTH}/{YEAR}'

HUD_X: 0

HUD_Y: 10
