author: Olloth
authors: [Olloth, LordNed]
database: false
depend: [Spout]
description: Adds Ambient Seasons to Minecraft using Spout.
main: me.ambientseasons.AmbientSeasons
name: AmbientSeasons
startup: postworld
version: '1.5.0'
commands:
   ashud:
     description: Enables or disables the Ambient Seasons HUD
     usage: /<command>
     aliases: [ashud, seasonshud]
   ashelp:
     description: Display the help file 
     usage: /<command>
     aliases: [ashelp, seasonshelp]
       
